Archery/Models/HomeViewModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Archery.Models
{
    public class HomeIndexViewModel
    {
        public IEnumerable<Tournament> Tournaments { get; set; }
    }
}

Archery/Controllers/ArchersController.cs
using Archery.Models;
using Archery.Tools;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Security.Cryptography;
using Archery.Areas.BackOffice.Models;
using Archery.Filters;
using System.Web.Services.Description;

namespace Archery.Controllers
{
    public class ArchersController : BaseController

    {

        // GET: Players
        public ActionResult Subscribe()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Subscribe([Bind(Exclude = "ID")]Archer archer)
        {
            if (DateTime.Now.AddYears(-9) <= archer.BirthDate)
            {
                //ViewBag.Erreur = "Date de naissance invalide";
                // return View();
                //ModelState.AddModelError("BirthDate", "Date de naissance invalide");
            }
            if (ModelState.IsValid)
            {
                //archer.Password = Extension.HashMD5(archer.Password);
                archer.Password = archer.Password.HashMD5();

                db.Configuration.ValidateOnSaveEnabled = false;
                db.Archers.Add(archer);
                db.SaveChanges();

                db.Configuration.ValidateOnSaveEnabled = true;
                //TempData["Message"] = "Archer Enregistré";
                Display("Archer enregistré");

                return RedirectToAction("index", "home");

            }

            return View();
        }

        [HttpGet]
        //[ArcherAuthentication]
        [Authentication(Type = "ARCHER")]
        public ActionResult SubscribeTournament(int? tournamentId)
        {
            if (tournamentId == null)
                return HttpNotFound();
            //ajout travail demande
            var tournament = db.Tournaments.SingleOrDefault(x => x.ID == tournamentId);
            Archer archer = (Archer)Session["ARCHER"];
            int countArcher = tournament.Shooters.Count(x => x.ArcherID == archer.ID);

            // controler si il reste des places pour le tournoi
            if (tournament.HasEnoughShooter())
            {
                Display("Vous ne pouvez pas vous inscrire, il n'y a plus de places disponibles", MessageType.ERROR);
                return View();
            }

            // contoler si l'archer s'est deja inscrit au tournoi
            if (countArcher > 0)
            {
                Display("Vous ne pouvez pas vous inscrire plusieurs fois à un tournoi", MessageType.ERROR);
                return View();
            }

            return View(tournament);
        }

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(AuthenticationLoginViewModel model)
        {
            var hash = model.Password.HashMD5();
            var archer = db.Archers.SingleOrDefault(x => x.Mail == model.Mail && x.Password == hash);
            if (archer == null)
            {
                Display("Login/mot de passe incorrect", MessageType.ERROR);
                return View();
            }
            else
            {
                Session["ARCHER"] = archer;
                //if (TempData["REDIRECT"] != null)
                //    return Redirect(TempData["REDIRECT"].ToString());
                //else
                    return RedirectToAction("index", "home");
            }

        }

        public ActionResult Logout()
        {
            Session.Remove("ARCHER");
            return RedirectToAction("index", "home");
        }



    }
}

Archery/Controllers/HomeController.cs
using Archery.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Archery.Controllers
{
    public class HomeController : BaseController
    {
        // GET: Home
        public ActionResult Index()
        {
            Session["test"] = "rtest";
            ViewData["Title"] = "Accueil";
            HomeIndexViewModel model = new HomeIndexViewModel();
            model.Tournaments = db.Tournaments.Include("Weapons")
                                                .Include("Pictures")
                                               .Where(x => x.StartDate >= DateTime.Now)
                                               .OrderBy(x => x.StartDate)
                                              .Take(20);
            return View(model);
        }

        //[Route ("a-propos")]
        public ActionResult About()
        {

            var modelInfo = new Info
            {
                DevName = "Anne",
                ContactMail = "anne@anne.com",
                CreatedDate = DateTime.Now
            };
            return View(modelInfo);
        }

        public ActionResult DetailTournament(int? id)
        {
            if (id == null)
                return HttpNotFound();
            var model = db.Tournaments.Include("Weapons")
                                             .Include("Pictures")
                                             .SingleOrDefault(x => x.ID == id);
            if (model == null)
                return HttpNotFound();
            return View(model);
        }
    }
}

Archery/Views/Home/About.cshtml
@model Archery.Models.Info
    @{ 
        ViewBag.Title = "A propos de ";
    }

<h1>A propos</h1>
    <div>
        <p>Dev: @Model.DevName</p>
        <p>&copy;@Model.CreatedDate</p>
        <p>Contact:@Model.ContactMail</p>
    </div>

Archery/Views/Home/DetailTournament.cshtml
@model Archery.Models.Tournament
@using Archery.Helpers;

@{
    ViewBag.Title = "Tournoi " + Model.Name;
}

<div class="jumbotron">
    <h1>@Model.Name</h1>
    <p>@Html.Raw(Model.Description)</p>
    <p>@Model.Price €</p>
    <p>@Model.Location</p>
    <div class="row">
        <div class="col-md-6">
            <p>Armes autorisées <span class="badge">@Model.Weapons.Count()</span></p>
            <ul class="list-group">
                @foreach (var item in Model.Weapons)
                {
                    <li class="list-group-item">@item.Name</li>
                }
            </ul>
        </div>
        <div class="col-md-6">
            <div class="row">
                @foreach (var picture in Model.Pictures)
                {
                    <div class="col-xs-6 col-md-3 thumbnail">
                        @Html.PictureTournament(picture)
                    </div>
                }
            </div>
        </div>
    </div>

    <p><a class="btn btn-primary btn-lg" href="@Url.Action("SubscribeTournament", "archers", new { tournamentId = Model.ID })" role="button">S'inscrire</a></p>
</div>

Archery/Views/Home/Index.cshtml
@model Archery.Models.HomeIndexViewModel
@using Archery.Helpers;

<div class="row">
    @foreach (var item in Model.Tournaments)
    {
        <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
                @if (item.Pictures?.Count() > 0)
                {
                    @Html.PictureTournament(item.Pictures.First(), "img-circle")
                }
                <div class="caption">
                    <h3>@item.Name</h3>
                    <p>@item.Location</p>
                    <p>@item.StartDate.ToString("ddd dd MMM yyyy ")</p>
                    @*@if (item.Weapons != null)
                        {
                        <ul>
                            @foreach (var weapon in item.Weapons)
                            {
                                <li>@weapon.Name</li>
                            }
                        </ul>
                        }*@
                   
                     <a class="btn btn-primary" href="@Url.Action("SubscribeTournament","Archers", new { tournamentId = item.ID })">S'inscrire</a><p><a href="@Url.RouteUrl("DetailsTournament", new { id=item.ID, name = item.Name })" class="btn btn-primary" role="button">Voir les détails</a> </p>
                </div>
            </div>
        </div>
    }
</div>